# Generated by Django 5.1.2 on 2024-11-05 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.IntegerField(verbose_name='Número de celular')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='Avatar')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de ultimos cambios de datos')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del producto')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría del producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Descuento')),
                ('number', models.PositiveIntegerField(verbose_name='Cantidad en inventario')),
                ('images', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imágenes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del proveedor')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la venta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.customer', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sale.product', verbose_name='Producto')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.supplier', verbose_name='Proveedor'),
        ),
    ]
