# Generated by Django 5.1.2 on 2024-11-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_remove_product_images_alter_customer_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marca del producto'),
        ),
    ]
