# Generated by Django 5.1.2 on 2024-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_customer_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
