# Generated by Django 5.1.3 on 2024-11-20 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_merge_0009_cart_cartitem_0009_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Referencia única del pedido'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Pagado'), ('pending', 'Pendiente'), ('cancelled', 'Cancelado')], default='pending', max_length=10, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la venta'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la venta')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total de la venta')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.cart', verbose_name='Carrito')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='sale.order', verbose_name='Item de orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.product', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('method', models.CharField(max_length=50, verbose_name='Metodo de pago')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id de transaccion')),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobacion del pago')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Cuotas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sale.order')),
            ],
        ),
    ]
