# Generated by Django 5.1.2 on 2024-11-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_merge_0009_cart_cartitem_0009_subscriber'),
        ('sale', '0012_alter_sale_options'),
    ]

    operations = [
    ]
