# Generated by Django 5.1.3 on 2024-11-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_alter_sale_options_sale_reference_sale_status_and_more'),
        ('sale', '0012_alter_sale_options'),
    ]

    operations = [
    ]
