# Generated by Django 5.1.2 on 2024-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
