# Generated by Django 5.1.3 on 2024-11-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_cart_cartitem'),
        ('sale', '0009_subscriber'),
    ]

    operations = [
    ]
