# Generated by Django 5.1.2 on 2024-11-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Referencia única del pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Pagado'), ('pending', 'Pendiente'), ('cancelled', 'Cancelado')], default='pending', max_length=10, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la venta'),
        ),
    ]
