# Generated by Django 5.1.2 on 2024-11-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
